version: '3.7'

services:
    app_database:
        container_name: wp_database
        image: mysql:8.0
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        links:
            - app_database
        depends_on: 
            - app_database
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST="${PMA_HOST}"

    wp_app:
        container_name: wp_app
        image: wordpress
        restart: always
        volumes:
            - ./www/:/var/www/html
        environment:
            WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
            WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
            WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
            WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
        ports:
            - "8000:80"
        depends_on: 
            - app_database

    nginx:
        container_name: nginx 
        build: ./docker/nginx
        restart: always
        ports: 
            - 8085:80
        volumes:
            - ./:/var/www
        depends_on: 
            - wp_app

volumes:
    db_data:



